site_name: log

theme:
  name: material
  logo: log.png
  favicon: log.png
  palette:
    scheme: slate
    primary: lime
    accent: lime
  font:
    text: Raleway
    code: JetBrains Mono
  features:
    - navigation.instant
    - search.suggest

repo_url: https://github.com/devOpifex/log
repo_name: Github
site_description: A convenient logger for R, shiny, and plumber.
site_author: Opifex
copyright: Copyright &copy; 2020 Opifex

google_analytics:
  - G-TZMQ98HS6D
  - auto

markdown_extensions:
    - admonition
    - meta
    - smarty
    - pymdownx.highlight:
        linenums: true
    - pymdownx.superfences
    - pymdownx.inlinehilite
    - attr_list
    - toc:
        permalink: True
        separator: "-"

nav:
  - Home: index.md
  - Guide:
    - Get Started: guide/get-started.md
    - Templates: guide/templates.md
    - Shiny: guide/shiny.md
    - Plumber: guide/plumber.md
    - Erratum: guide/erratum.md
  - Changelog: misc/changelog.md 
  - Code of Conduct: misc/coc.md
  - License: misc/license.md
